title: "Bruno Baère // Portfolio"
description: "C++ Software Engineer and researcher specializing in Game AI, Dynamic Difficulty Adaptivity, and Computer Graphics."
url: "https://killerasus.github.io"
